remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Aniket Bhosale Portfolio
description: **Mechanical Design + Robotics Simulation | ROS2 路 SolidWorks 路 Python 路 C++ 路 FEA | | Seeking Design & Robotics Roles**
logo: /images/photo.jpg
show_downloads: false

# Simplified navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
